# Path to the XES logs
log_path: "data/xes/running-example.xes"
# log_path: "data/xes/Road_Traffic_Fine_Management_Process.xes"
#log_path: "data/xes/BPI Challenge 2017.xes"

# Process discovery method: "alpha", "heuristic" or "inductive"
#process_model_type: "alpha"
process_model_type: "heuristic"
#process_model_type: "inductive"

# Heuristic parameters (only used if process_model_type == "heuristic")
heuristic:
  dependency_threshold: 0.5
  and_threshold: 0.4
  loop_two_threshold: 0.3

# Inductive parameters (only used if process_model_type == "inductive")
inductive:
  noise_threshold: 0.2
  disable_fallthroughs: false

decision_tree:
  # Default tree (baseline)
  criterion: "gini"
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: "sqrt"
  random_state: 42
  class_weight: "balanced"
  ccp_alpha: 0.0

  # Aggressive pruning parameters
  prune_depth: 3
  prune_min_samples_leaf: 10

